### ISSUE TITLE
Game Design direction and 'vision'

### ISSUE THREAD

**Issue by Chargoal** [forthfora/pearlcat#1]
Pearlcat is a big new hyped up mod and it's exceptionally cool in technical execution. I didn't have time to have my hands on it yet, but checked the steam page, trailer and reviews from your testers. Not considering power balance, I saw a big flaw - **design direction.** 

It's interesting to play with different pearl combinations, but all of them lead to something the game already has to offer: mobility of Artificer, spear-creation of Spearmaster, some other general utility, and the thing that bothers me about it - it's all disparate and disconnected, which leads to the feeling of Pearlcat's kit being 'overloaded' with features, which are not necessary to its identity.

I offer to take a look at identity and thematic design of Pearlcat and decide upon something unifying about it, other than pearls. 
I think there can be 3 solutions to this issue:
1. Your game design is exactly how you intended it to be played and you want it to be like that - then there is no issue. I just see that it could be something more than just 'overloaded' slugcat with pearls.
2. You (primarly Geahgeah, who is marked as "Design" part of the mod) take a look at the design yourself and think how you can change it, to a have a better thematic clarity in its gameplay. However the team of 3 people can only do so much and you are already succeeding with flying colors in Art and Technical department, and I think it's okay for you to focus on that.
3. I offer my direct help. I'm a game designer student with a lot of knowledge in mechanical and thematical game desing. Additionaly, I have a lot of free time and am willing to take a dip into RW's modding - your amazing mod specifically. If you're interested - message me in some way or just answer to issue (I'd prefer private discussions from there on out)

**Comment by forthfora** [comment]
feedback is always good, if you would like to talk more privately please contact me via discord (@forthbridge)
