### ISSUE TITLE
Trying to throw things after you [SECRET SPOILER WARNING] makes you instantly explode and die

### ISSUE THREAD

**Issue by Alceris** [forthfora/pearlcat#23]
When you possess a creature and then release them, throwing seemingly any weapon (so far it's happened both with pearl spears and flashbangs) has a high chance of just instantly killing you in a violent explosion for no apparent reason.

**Comment by forthfora** [comment]
thanks for the report, just to let you know I've come around to finishing off the next small update, it should be fixed then

**Comment by Alceris** [comment]
Oh right, I also just remembered: While possessing a creature, you the slugcat can still be hit by things, up to and including the creature you're possessing; for example I possessed a Miros Bird and was consequently able to bite and kill the phantom scug following the possessed bird's torso.
